import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '',
    default: 'Create Next App',
  },
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
